### PR TITLE
Fix SSO authentication on keycloak activation

### PR DESCRIPTION
**Pull request by arso**
In order to activate Keycloak internal sso on already existing
installations run engine-setup with the following parameters:

```engine-setup --otopi-environment="OVESETUP_CONFIG/keycloakEnable=bool:True```

Those configuration parameters can be provided with answer file ie:
```engine-setup --config-append=<path_to_config_file>```

This patch requires:
* https://github.com/oVirt/ovirt-engine/pull/379
* https://github.com/oVirt/ovirt-dwh/pull/39
and resolves:
* https://github.com/oVirt/ovirt-engine-keycloak/issues/19
* https://github.com/oVirt/ovirt-engine-keycloak/issues/39

Signed-off-by: Artur Socha <asocha@redhat.com>

### CODE REVIEW

**Review by mwperina — APPROVED** [review]
+1

**Review by almusil — APPROVED** [review]
LGTM

**Comment by didib** [comment]
Also:
> Those configuration parameters can be provided with answer file ie:
> engine-setup --config=<path_to_answer_file>

Please fix (perhaps also in the doc PR): Should be '--config-append', not '--config'. There is actually no "normal" flow where '--config' is useful. Not sure why Alon insisted on calling it so, back then... '--config' will make engine-setup not check the content of /etc/ovirt-engine-setup.conf.d/ . This is its "config", and '--config' tells it to look elsewhere.

**Comment by arso** [comment]
Please see the description of recent changes that I posted there https://github.com/oVirt/ovirt-engine/pull/379#issuecomment-1141285596

**Review by mwperina — APPROVED** [review]
+1

**Pull request merged**
