### PR TITLE
Set engine admin with correct password

### PR DESCRIPTION
**Pull request by didib**

### CODE REVIEW

**Review by mwperina — APPROVED** [review]
+1

**Comment by didib** [comment]
@mwperina Thanks for reviewing. Do we want a bug (and a link) for this?

Change the text in 'Keycloak [admin] and [admin@ovirt] password:'?

Clarify (in code/docs/elsewhere) that there are two engine admins (an internal one and a keycloak one)?

**Comment by didib** [comment]
Created https://bugzilla.redhat.com/show_bug.cgi?id=2120602

**Review by mwperina — APPROVED** [review]
+1

**Pull request merged**
